POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "vinicius@email.com",
    "password": "123456"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{   
    "name": "Vinicius",
    "email": "vinicius@email.com",
    "password": "123456"
}

###
POST http://localhost:3000/users/tasks
Content-Type: application/json
{   
    "title": "Task 1",
    "description": "Description of task 1",
    "priority": "high",
    "completed": false
}

###
GET http://localhost:3000/user/tasks
Content-Type: application/json 

###
GET http://localhost:3000/user/tasks/1
Content-Type: application/json 
